.# Identify Licence Status (ZS Associates Case Study)

### Points to identify this problem 

In [30]:
# Importing required packages for model

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import pickle as pk

sns.set(style="ticks", color_codes=True)
pd.set_option('display.max_columns', None)
%matplotlib inline

### Data loading and Exploratory Data Analysis

In [31]:
#Importing Train Dataset and Test Dataset

dataset = pd.read_csv("train_file.csv")
testset = pd.read_csv("test_file.csv")

C:\Users\ADMIN\Anaconda3\envs\deeplearning\lib\site-packages\IPython\core\interactiveshell.py:3051: DtypeWarning: Columns (9) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [32]:
# Let's create the functions to perform missing value imputations and peform operations easily

# let's create a variable to replace NA with the random sample imputation
def impute_na(df, variable):
    '''
    This function is defined to perform random sampleing and then imputeing missing values from that samples.
    '''
    # random sampling
    df[variable+'_random'] = df[variable]
        
    # extract the random sample to fill the na
    random_sample = df[variable].dropna().sample(df[variable].isnull().sum(), random_state=0)
    
    # pandas needs to have the same index in order to merge datasets
    random_sample.index = df[df[variable].isnull()].index
    
    df.loc[df[variable].isnull(), variable+'_random'] = random_sample
    
# let's create a variable to replace NA with the most frequent label
def impute_na_most_frequent(df, variable):
    '''
    This function has defined to perform most frequent value impution for the missing values.
    '''
    most_frequent_category = df.groupby([variable])[variable].count().sort_values(ascending=False).index[0]
    df[variable+ '_most_frequent'] = df[variable].fillna(most_frequent_category)
    
# let's create a variable to capture NA to indicate missingness
def impute_na_missing(df, variable):
    '''
    This function has defined to mark the misssingness of that value in the dataset.
    '''
    # add additional variable to indicate missingness
    df[variable+'_NA'] = np.where(df[variable].isnull(), 1, 0)
    
def impute_na_mean(df, variable):
    '''
    This function has defined to perform mean value imputation in the dataset.
    '''
    mean = df[variable].mean()
    df[variable+'_mean'] = df[variable].fillna(mean)

In [33]:
impute_na(dataset,'ZIP CODE')
impute_na(dataset,'APPLICATION REQUIREMENTS COMPLETE')
impute_na(dataset,'LICENSE TERM START DATE')
impute_na(dataset,'LICENSE TERM EXPIRATION DATE')
impute_na(dataset,'LICENSE APPROVED FOR ISSUANCE')
impute_na(dataset,'PAYMENT DATE')

impute_na_most_frequent(dataset,'WARD PRECINCT')
impute_na_most_frequent(dataset,'WARD')
impute_na_most_frequent(dataset,'PRECINCT')
impute_na_most_frequent(dataset,'POLICE DISTRICT')
impute_na_most_frequent(dataset,'LICENSE STATUS CHANGE DATE')
impute_na_most_frequent(dataset,'LATITUDE')
impute_na_most_frequent(dataset,'LONGITUDE')
impute_na_most_frequent(dataset,'DOING BUSINESS AS NAME')
impute_na_most_frequent(dataset,'LICENSE NUMBER')

impute_na_mean(dataset,'SSA')

impute_na_missing(dataset,'WARD PRECINCT')
impute_na_missing(dataset,'WARD')
impute_na_missing(dataset,'PRECINCT')
impute_na_missing(dataset,'POLICE DISTRICT')
impute_na_missing(dataset,'SSA')
impute_na_missing(dataset,'LICENSE STATUS CHANGE DATE')
impute_na_missing(dataset,'LATITUDE')
impute_na_missing(dataset,'LONGITUDE')

dataset = dataset.drop(['ZIP CODE', 'APPLICATION REQUIREMENTS COMPLETE','LICENSE TERM START DATE',
                        'LICENSE TERM EXPIRATION DATE','LICENSE APPROVED FOR ISSUANCE','APPLICATION CREATED DATE',
                        'PAYMENT DATE','WARD PRECINCT','WARD','PRECINCT','POLICE DISTRICT','LICENSE STATUS CHANGE DATE',
                        'LATITUDE','LONGITUDE','LOCATION','SSA','DOING BUSINESS AS NAME','LICENSE NUMBER'],axis=1)

# dataset.head()

In [34]:
impute_na(testset,'ZIP CODE')
impute_na(testset,'APPLICATION REQUIREMENTS COMPLETE')
impute_na(testset,'LICENSE TERM START DATE')
impute_na(testset,'LICENSE TERM EXPIRATION DATE')
impute_na(testset,'LICENSE APPROVED FOR ISSUANCE')
impute_na(testset,'PAYMENT DATE')

impute_na_most_frequent(testset,'WARD PRECINCT')
impute_na_most_frequent(testset,'WARD')
impute_na_most_frequent(testset,'PRECINCT')
impute_na_most_frequent(testset,'POLICE DISTRICT')
impute_na_most_frequent(testset,'LICENSE STATUS CHANGE DATE')
impute_na_most_frequent(testset,'LATITUDE')
impute_na_most_frequent(testset,'LONGITUDE')
impute_na_most_frequent(testset,'DOING BUSINESS AS NAME')
impute_na_most_frequent(testset,'LICENSE NUMBER')

impute_na_mean(testset,'SSA')

impute_na_missing(testset,'WARD PRECINCT')
impute_na_missing(testset,'WARD')
impute_na_missing(testset,'PRECINCT')
impute_na_missing(testset,'POLICE DISTRICT')
impute_na_missing(testset,'SSA')
impute_na_missing(testset,'LICENSE STATUS CHANGE DATE')
impute_na_missing(testset,'LATITUDE')
impute_na_missing(testset,'LONGITUDE')

testset = testset.drop(['ZIP CODE', 'APPLICATION REQUIREMENTS COMPLETE','LICENSE TERM START DATE',
                        'LICENSE TERM EXPIRATION DATE','LICENSE APPROVED FOR ISSUANCE','APPLICATION CREATED DATE',
                        'PAYMENT DATE','WARD PRECINCT','WARD','PRECINCT','POLICE DISTRICT','LICENSE STATUS CHANGE DATE',
                        'LATITUDE','LONGITUDE','LOCATION','SSA','DOING BUSINESS AS NAME','LICENSE NUMBER'],axis=1)
# testset.head()

## Handleing columns having Datetime information

we need to extract the weekday, month and year from the respective date column.

In [35]:
def time_vars_with_day(df, var):
    '''
    Define a function to extract the Year, Month and day information from the datetime column features.
    
    '''
    df[var +'_Year'] = pd.DatetimeIndex(df[var]).year
        
    df[var +'_Month'] = pd.DatetimeIndex(df[var]).month
    
    df[var +'_Day'] = pd.DatetimeIndex(df[var]).weekday
    

In [36]:
time_vars_with_day(dataset,'DATE ISSUED')
time_vars_with_day(dataset,'APPLICATION REQUIREMENTS COMPLETE_random')
time_vars_with_day(dataset,'LICENSE TERM START DATE_random')
time_vars_with_day(dataset,'LICENSE TERM EXPIRATION DATE_random')
time_vars_with_day(dataset,'LICENSE APPROVED FOR ISSUANCE_random')
time_vars_with_day(dataset,'PAYMENT DATE_random')
time_vars_with_day(dataset,'LICENSE STATUS CHANGE DATE_most_frequent')

dataset = dataset.drop(['DATE ISSUED','APPLICATION REQUIREMENTS COMPLETE_random','LICENSE TERM START DATE_random',
             'LICENSE TERM EXPIRATION DATE_random','LICENSE APPROVED FOR ISSUANCE_random','PAYMENT DATE_random','LICENSE STATUS CHANGE DATE_most_frequent'], axis = 1)
# dataset.head()

In [37]:
time_vars_with_day(testset,'DATE ISSUED')
time_vars_with_day(testset,'APPLICATION REQUIREMENTS COMPLETE_random')
time_vars_with_day(testset,'LICENSE TERM START DATE_random')
time_vars_with_day(testset,'LICENSE TERM EXPIRATION DATE_random')
time_vars_with_day(testset,'LICENSE APPROVED FOR ISSUANCE_random')
time_vars_with_day(testset,'PAYMENT DATE_random')
time_vars_with_day(testset,'LICENSE STATUS CHANGE DATE_most_frequent')

testset = testset.drop(['DATE ISSUED','APPLICATION REQUIREMENTS COMPLETE_random','LICENSE TERM START DATE_random',
             'LICENSE TERM EXPIRATION DATE_random','LICENSE APPROVED FOR ISSUANCE_random','PAYMENT DATE_random','LICENSE STATUS CHANGE DATE_most_frequent'], axis = 1)
# testset.head()

In [38]:
# Write a function for frequency based encodeing

def frequency_Encodeing(df,var):
    '''
    This function has defined to map the frequency based count in the dataset to perform encodeing.
    '''
    count_dict = df[var].value_counts().to_dict()
    df[var + '_freq'] = df[var].map(count_dict)

In [39]:
#Encodeing on the dataset

frequency_Encodeing(dataset,'LEGAL NAME')
frequency_Encodeing(dataset,'SITE NUMBER')
frequency_Encodeing(dataset,'DOING BUSINESS AS NAME_most_frequent')
frequency_Encodeing(dataset,'ADDRESS')
frequency_Encodeing(dataset,'CITY')
frequency_Encodeing(dataset,'ZIP CODE_random')
frequency_Encodeing(dataset,'STATE')
frequency_Encodeing(dataset,'LICENSE CODE')
frequency_Encodeing(dataset,'LICENSE NUMBER_most_frequent')
frequency_Encodeing(dataset,'LICENSE DESCRIPTION')
frequency_Encodeing(dataset,'WARD PRECINCT_most_frequent')

#Encodeing on the testset
frequency_Encodeing(testset,'LEGAL NAME')
frequency_Encodeing(testset,'SITE NUMBER')
frequency_Encodeing(testset,'DOING BUSINESS AS NAME_most_frequent')
frequency_Encodeing(testset,'ADDRESS')
frequency_Encodeing(testset,'CITY')
frequency_Encodeing(testset,'ZIP CODE_random')
frequency_Encodeing(testset,'STATE')
frequency_Encodeing(testset,'LICENSE CODE')
frequency_Encodeing(testset,'LICENSE NUMBER_most_frequent')
frequency_Encodeing(testset,'LICENSE DESCRIPTION')
frequency_Encodeing(testset,'WARD PRECINCT_most_frequent')



dataset = dataset.drop(['LEGAL NAME','SITE NUMBER','DOING BUSINESS AS NAME_most_frequent','ADDRESS','CITY','STATE','LICENSE CODE',
                        'LICENSE NUMBER_most_frequent','LICENSE DESCRIPTION','WARD PRECINCT_most_frequent','ZIP CODE_random'], axis = 1)

testset = testset.drop(['LEGAL NAME','SITE NUMBER','DOING BUSINESS AS NAME_most_frequent','ADDRESS','CITY','STATE','LICENSE CODE',
                        'LICENSE NUMBER_most_frequent','LICENSE DESCRIPTION','WARD PRECINCT_most_frequent','ZIP CODE_random'], axis = 1)


In [40]:
## Apply one hot encodeing on the application type and conditional approval

dataset = pd.get_dummies(dataset, drop_first=True, columns=['APPLICATION TYPE','CONDITIONAL APPROVAL'])
testset = pd.get_dummies(testset, drop_first=True, columns=['APPLICATION TYPE','CONDITIONAL APPROVAL'])

In [41]:
# Need to encode dependen variable columns
LICENSE_STATUS = {'AAI':0,'AAC':1,'REV':2,'REA':3,'INQ':4}
dataset['LICENSE STATUS'] = dataset['LICENSE STATUS'].map(LICENSE_STATUS)

### Check columns from Train dataset and Test dataset

In [42]:
trainColumns = dataset.columns.values

In [43]:
missing_column = []
for value in testset.columns.values:
    if value in dataset.columns.values:
        continue
    else:
        print (value)
        missing_column.append(value)
missing_column

APPLICATION TYPE_C_SBA


['APPLICATION TYPE_C_SBA']

In [44]:
testset = testset.drop(missing_column, axis = 1)

## Completed with Data Preprocessing

## Feature Scaleing

In [45]:
models = []
acc = []
precision = []
recall = []
f1 = []

In [46]:
from imblearn.over_sampling import SMOTE
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [47]:
dataSub = dataset[(dataset['LICENSE STATUS'] == 3) | (dataset['LICENSE STATUS'] == 4) | (dataset['LICENSE STATUS'] == 5)]

In [48]:
X_sub = dataSub.drop(['ID','LICENSE ID','ACCOUNT NUMBER','LICENSE STATUS'], axis=1)
y_sub = dataSub[['LICENSE STATUS']]

In [49]:
col = list(X_sub.columns.values)
col2 = list(X_sub.columns.values)

In [50]:
oversampler=SMOTE(kind='regular',k_neighbors=1)
X_res, y_res = oversampler.fit_sample(X_sub, y_sub)

C:\Users\ADMIN\Anaconda3\envs\deeplearning\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [51]:
X_resDF = pd.DataFrame(X_res, columns= col)

In [52]:
y_resDF = pd.DataFrame(y_res, columns=['LICENSE STATUS'])

In [53]:
X_fin = dataset.drop(['ID','LICENSE ID','ACCOUNT NUMBER','LICENSE STATUS'], axis=1).append(X_resDF)
y_fin = dataset[['LICENSE STATUS']].append(y_resDF)

X = dataset.drop(['ID','LICENSE ID','ACCOUNT NUMBER','LICENSE STATUS'], axis=1).append(X_resDF).values
y = dataset[['LICENSE STATUS']].append(y_resDF).values

test = testset.drop(['ID','LICENSE ID','ACCOUNT NUMBER'], axis=1).values

In [54]:
sm = SMOTE('minority',random_state=101)
X_res, y_res = oversampler.fit_sample(X, y)

C:\Users\ADMIN\Anaconda3\envs\deeplearning\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [55]:
X_train, X_test, y_train, y_test = train_test_split(X_res, y_res, test_size=0.25, random_state=101)

In [56]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)


In [57]:
test_data = sc.transform(test)

# Load Random Forest Classification Model to get Feature importance upto 0.95

In [67]:
# Fitting Random Forest Classification to the Training set
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators = 300, criterion = 'entropy', random_state = 0)
rf.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=300, n_jobs=1,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [68]:
def feature_select(X, y, cols, cutoff):
    regressor = RandomForestClassifier(n_estimators = 300, random_state = 0)
    regressor.fit(X, y)
    global feat_imps
    feat_imps = pd.concat([pd.DataFrame(cols, columns=['Features']),
                       pd.DataFrame(rf.feature_importances_, columns=['Importances'])],axis=1)
    feat_imps = feat_imps.sort_values(['Importances'], ascending=False)
    feat_imps['Cumulative Importances'] = feat_imps['Importances'].cumsum()
    #print(feat_imps)
    feat_imps = feat_imps[feat_imps['Cumulative Importances'] < cutoff]
    return feat_imps['Features'].tolist()

In [69]:
cols = dataset.columns[4:]

In [70]:
imp_cols = feature_select(X_res, y_res, cols, 0.95)
feat_imps

Features  Importances  \
11                   LICENSE STATUS CHANGE DATE_NA     0.101344   
34    LICENSE STATUS CHANGE DATE_most_frequent_Day     0.054781   
45                WARD PRECINCT_most_frequent_freq     0.052560   
8                                      PRECINCT_NA     0.050066   
32   LICENSE STATUS CHANGE DATE_most_frequent_Year     0.046577   
40                            ZIP CODE_random_freq     0.042983   
33  LICENSE STATUS CHANGE DATE_most_frequent_Month     0.040681   
9                               POLICE DISTRICT_NA     0.040562   
20             LICENSE TERM START DATE_random_Year     0.033178   
31                         PAYMENT DATE_random_Day     0.030495   
6                                 WARD PRECINCT_NA     0.030260   
28        LICENSE APPROVED FOR ISSUANCE_random_Day     0.028186   
39                                       CITY_freq     0.027086   
7                                          WARD_NA     0.024477   
23        LICENSE TERM EXPIRATION DATE_random_Year     0.023869   
14                                DATE ISSUED_Year     0.023622   
44                        LICENSE DESCRIPTION_freq     0.023371   
25         LICENSE TERM EXPIRATION DATE_random_Day     0.023136   
42                               LICENSE CODE_freq     0.022449   
21            LICENSE TERM START DATE_random_Month     0.022194   
26       LICENSE APPROVED FOR ISSUANCE_random_Year     0.018562   
13                                    LONGITUDE_NA     0.017216   
29                        PAYMENT DATE_random_Year     0.016731   
17   APPLICATION REQUIREMENTS COMPLETE_random_Year     0.016440   
15                               DATE ISSUED_Month     0.015381   
12                                     LATITUDE_NA     0.014639   
22              LICENSE TERM START DATE_random_Day     0.012172   
35                                 LEGAL NAME_freq     0.011679   
27      LICENSE APPROVED FOR ISSUANCE_random_Month     0.011598   
37       DOING BUSINESS AS NAME_most_frequent_freq     0.011260   
30                       PAYMENT DATE_random_Month     0.010949   
19    APPLICATION REQUIREMENTS COMPLETE_random_Day     0.009755   
24       LICENSE TERM EXPIRATION DATE_random_Month     0.009552   
38                                    ADDRESS_freq     0.009241   
0                               WARD_most_frequent     0.009059   
3                           LATITUDE_most_frequent     0.008778   

    Cumulative Importances  
11                0.101344  
34                0.156126  
45                0.208685  
8                 0.258752  
32                0.305328  
40                0.348311  
33                0.388993  
9                 0.429555  
20                0.462733  
31                0.493228  
6                 0.523488  
28                0.551674  
39                0.578759  
7                 0.603236  
23                0.627106  
14                0.650728  
44                0.674098  
25                0.697235  
42                0.719684  
21                0.741878  
26                0.760441  
13                0.777657  
29                0.794387  
17                0.810827  
15                0.826208  
12                0.840846  
22                0.853018  
35                0.864697  
27                0.876295  
37                0.887555  
30                0.898504  
19                0.908259  
24                0.917812  
38                0.927052  
0                 0.936111  
3                 0.944889

In [71]:
X = X_fin[imp_cols].values

In [72]:
y = y_fin['LICENSE STATUS'].values
y.shape

(85901,)

In [73]:
sm = SMOTE('minority',random_state=101)
X_res, y_res = oversampler.fit_sample(X, y)

In [74]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_res, y_res, test_size = 0.25, random_state = 100)

In [75]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler, MinMaxScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
meanX = sc_X.mean_
varX = sc_X.var_

X_test = sc_X.transform(X_test)

# DEEP LEARNING

In [76]:
# Importing the Keras libraries and packages
import keras
from keras.utils import plot_model
from keras.models import Model,Sequential,load_model
from keras.layers import Input, Flatten, Dense, Dropout
from keras.layers.merge import concatenate
from keras import backend as K
from keras.callbacks import ModelCheckpoint


from keras.layers import Dense, Activation, Embedding, LeakyReLU, BatchNormalization
from keras.activations import relu, sigmoid
from keras.layers import LeakyReLU

Using TensorFlow backend.


In [77]:
def f1(y_true, y_pred):
    def recall(y_true, y_pred):
        """Recall metric.

        Only computes a batch-wise average of recall.

        Computes the recall, a metric for multi-label classification of
        how many relevant items are selected.
        """
        true_positives = K.sum(K.round(K.clip(y_true * y_pred, 0, 1)))
        possible_positives = K.sum(K.round(K.clip(y_true, 0, 1)))
        recall = true_positives / (possible_positives + K.epsilon())
        return recall

    def precision(y_true, y_pred):
        """Precision metric.

        Only computes a batch-wise average of precision.

        Computes the precision, a metric for multi-label classification of
        how many selected items are relevant.
        """
        true_positives = K.sum(K.round(K.clip(y_true * y_pred, 0, 1)))
        predicted_positives = K.sum(K.round(K.clip(y_pred, 0, 1)))
        precision = true_positives / (predicted_positives + K.epsilon())
        return precision
    precision = precision(y_true, y_pred)
    recall = recall(y_true, y_pred)
    return 2*((precision*recall)/(precision+recall+K.epsilon()))

In [78]:
import tensorflow as tf
from sklearn.metrics import roc_auc_score

def auroc(y_true, y_pred):
    return tf.py_func(roc_auc_score, (y_true, y_pred), tf.double)

In [79]:
input_shape = X_train.shape[1]
input_shape

36

In [80]:
input_layer = Input(shape=(input_shape,))

hidden1 = Dense(units = X_train.shape[1],kernel_initializer = 'uniform',
                activation = 'relu')(input_layer)

dropout = Dropout(rate=0.2)(hidden1)

hidden2 = Dense(units = 19,kernel_initializer = 'uniform',
                activation = 'relu')(hidden1)

dropout = Dropout(rate=0.2)(hidden2)

output_layer = Dense(units = 5,kernel_initializer = 'uniform',
                activation = 'softmax')(dropout)

model = Model(inputs=input_layer, outputs=output_layer)

# Compiling the ANN

model.compile(optimizer = 'adam', 
              loss = 'categorical_crossentropy', 
              metrics = ['acc'])

# summarize layers
print(model.summary())

Instructions for updating:
If using Keras pass *_constraint arguments to layers.
Model: "model_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         (None, 36)                0         
_________________________________________________________________
dense_1 (Dense)              (None, 36)                1332      
_________________________________________________________________
dense_2 (Dense)              (None, 19)                703       
_________________________________________________________________
dropout_2 (Dropout)          (None, 19)                0         
_________________________________________________________________
dense_3 (Dense)              (None, 5)                 100       
Total params: 2,135
Trainable params: 2,135
Non-trainable params: 0
_________________________________________________________________
None


In [81]:
# checkpoint
filepath="Best_Model.h5"
checkpoint = ModelCheckpoint(filepath, monitor='val_auroc', verbose=1, save_best_only=True, mode='max')
callbacks_list = [checkpoint]

In [83]:
from keras.utils import to_categorical
model.fit(X_train, 
          y = to_categorical(y_train),
          verbose=1,
          validation_split=0.25,
          shuffle=True,
          callbacks = callbacks_list,
          batch_size = 1024,
          epochs = 100)


Train on 155812 samples, validate on 51938 samples
Epoch 1/100
155812/155812 [==============================] - 3s 21us/step - loss: 1.0164 - acc: 0.6512 - val_loss: 0.4704 - val_acc: 0.8397
Epoch 2/100
 13312/155812 [=>............................] - ETA: 1s - loss: 0.4962 - acc: 0.815

C:\Users\ADMIN\Anaconda3\envs\deeplearning\lib\site-packages\keras\callbacks\callbacks.py:707: RuntimeWarning: Can save best model only with val_auroc available, skipping.
  'skipping.' % (self.monitor), RuntimeWarning)


155812/155812 [==============================] - 2s 10us/step - loss: 0.3467 - acc: 0.8685 - val_loss: 0.2033 - val_acc: 0.9258
Epoch 3/100
155812/155812 [==============================] - 1s 10us/step - loss: 0.2151 - acc: 0.9208 - val_loss: 0.1600 - val_acc: 0.9343
Epoch 4/100
155812/155812 [==============================] - 2s 11us/step - loss: 0.1803 - acc: 0.9313 - val_loss: 0.1447 - val_acc: 0.9421
Epoch 5/100
155812/155812 [==============================] - 2s 10us/step - loss: 0.1642 - acc: 0.9376 - val_loss: 0.1348 - val_acc: 0.9455
Epoch 6/100
155812/155812 [==============================] - 1s 9us/step - loss: 0.1518 - acc: 0.9418 - val_loss: 0.1250 - val_acc: 0.9496
Epoch 7/100
155812/155812 [==============================] - 2s 10us/step - loss: 0.1410 - acc: 0.9464 - val_loss: 0.1162 - val_acc: 0.9551
Epoch 8/100
155812/155812 [==============================] - 2s 10us/step - loss: 0.1309 - acc: 0.9514 - val_loss: 0.1077 - val_acc: 0.9595
Epoch 9/100
155812/155812 [======

In [84]:
model.predict(X_test)

array([[1.3453695e-29, 7.8850053e-03, 9.9211496e-01, 0.0000000e+00,
        1.5019857e-28],
       [1.0000000e+00, 1.8700899e-18, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00],
       [1.0000000e+00, 3.8080801e-20, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00],
       ...,
       [2.7684230e-34, 9.9999988e-01, 1.2393610e-07, 0.0000000e+00,
        3.8797492e-29],
       [9.5928076e-17, 4.7907945e-02, 9.5209205e-01, 5.8538919e-30,
        1.6180131e-15],
       [1.7933169e-20, 2.8385304e-02, 9.7161466e-01, 0.0000000e+00,
        1.8588262e-18]], dtype=float32)

In [95]:
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, precision_score, recall_score, f1_score
predicted = model.predict(X_test)

#predicted = np.argmax(predicted, axis=1)

predicted = np.argmax(model.predict(X_test), axis=1)
accuracy_score(y_test, predicted)

0.9936317689530686

In [96]:
predicted

array([2, 0, 0, ..., 1, 2, 2], dtype=int64)

In [98]:
print('Confusion Matrix for ANN: \n',confusion_matrix(y_test, predicted))
print('Accuracy for ANN: \n',accuracy_score(y_test, predicted))
acc.append(accuracy_score(y_test, predicted))
print('Precision for ANN: \n',precision_score(y_test, predicted, average='micro'))
precision.append(precision_score(y_test, predicted, average='micro'))
print('Recall for ANN: \n',precision_score(y_test, predicted, average='micro'))
recall.append(recall_score(y_test, predicted, average='micro'))
print('f1_score for ANN: \n',f1_score(y_test, predicted, average='micro'))

Confusion Matrix for ANN: 
 [[13935     0     0     0     0]
 [    0 13495   418     2     0]
 [    0    21 13765     0     0]
 [    0     0     0 13801     0]
 [    0     0     0     0 13813]]
Accuracy for ANN: 
 0.9936317689530686
Precision for ANN: 
 0.9936317689530686
Recall for ANN: 
 0.9936317689530686
f1_score for ANN: 
 0.9936317689530686


In [ ]:
# def create_model(layers, activation):
#     model = Sequential()
#     for i, nodes in enumerate(layers):
#         if i==0:
#             model.add(Dense(nodes,input_dim=X_train.shape[1]))
#             model.add(Activation(activation))
#         else:
#             model.add(Dense(nodes))
#             model.add(Activation(activation))
#     model.add(Dense(1)) # Note: no activation beyond this point
    
#     model.compile(optimizer='adam', loss='categorical_crossentropy',metrics=['accuracy'])
#     return model
    
# model = KerasClassifier(build_fn=create_model, verbose=0)

In [ ]:
# layers = [[20], [40, 20], [45, 30, 15]]
# activations = ['sigmoid', 'relu']
# param_grid = dict(layers=layers, activation=activations, batch_size = [128, 256], epochs=[30])
# grid = GridSearchCV(estimator=model, param_grid=param_grid)

In [ ]:
# grid_result = grid.fit(X_train, y_train)

In [ ]:
# [grid_result.best_score_,grid_result.best_params_]

In [ ]:
# predicted = np.argmax(grid.predict(X_test), axis=1)

In [ ]:
# cm = confusion_matrix(y_test, predicted)

In [ ]:
# score=accuracy_score(y_test,predicted)